name: pyrception
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - cpuonly
  - dotmap
  - h5py
  - ipykernel
  - loguru
  - matplotlib
  - numpy
  - opencv
  - pip
  - python-decouple
  - pytorch
  - scikit-image
  - scipy
  - seaborn
  - torchvision
  - tqdm
  - pip:
    - -e .