name: pyrception
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - h5py
  - ipykernel
  - ipympl
  - loguru
  - matplotlib
  - numpy
  - opencv
  - pip
  - python-decouple
  - pydata-sphinx-theme
  - pytorch
  - pytorch-cuda
  - scikit-image
  - scipy
  - seaborn
  - sphinx
  - torchvision
  - tqdm
  - pip:
      - furo
      - -e .
