[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pyrception"]

[project]
authors = [{ name = "Alexander Hadjiivanov" }]
name = "pyrception"
version = "0.3.4post2"
requires-python = ">= 3.11"
dependencies = [
    "av",
    "bokeh",
    "loguru",
    "matplotlib",
    "moviepy",
    "numpy",
    "omegaconf",
    "platformdirs",
    "scikit-image",
    "scipy",
    "tqdm",
]
dynamic = ["readme"]

[tool.setuptools.dynamic]
readme = { file = ["README.md"], content-type = "text/markdown" }

[dependency-groups]
cli = ["cloup"]
events = ["faery", "event-camera-drivers"]
dev = ["black", "py-spy", "pytest"]
torch = ["torch"]
ipy = ["ipykernel", "ipywidgets"]
docs = [
    "mkdocs",
    "mike",
    "mkdocs-jupyter",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-macros-plugin",
    { include-group = "ipy" },
]
all = [
    { include-group = "cli" },
    { include-group = "events" },
    { include-group = "dev" },
    { include-group = "torch" },
    { include-group = "ipy" },
    { include-group = "docs" },

]

[project.scripts]
pyrception = "pyrception.gui.main:run"

[tool.ruff.format]
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ruff.lint.isort]
from-first = false
force-single-line = true
force-sort-within-sections = true
length-sort = true
lines-after-imports = 1
order-by-type = true
forced-separate = [
    "future",
    "typing",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
    "pyrception",
]
relative-imports-order = "closest-to-furthest"
