[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pyrception"]

[project]
authors = [{ name = "Alexander Hadjiivanov" }]
name = "pyrception"
version = "0.3.4post2"
requires-python = ">= 3.11"
description = "A biosensor simulation toolkit."
keywords = [
    "bioinspired vision",
    "neuromorphic sensing",
    "simulation",
    "retina",
    "neuroscience",
]
dependencies = [
    "av",
    "bokeh",
    "environs",
    "loguru",
    "matplotlib",
    "moviepy",
    "numpy",
    "platformdirs",
    "scikit-image",
    "scipy",
    "tqdm",
]
dynamic = ["readme"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Visualization",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[tool.setuptools.dynamic]
readme = { file = ["readme.md"], content-type = "text/markdown" }

[dependency-groups]
cli = ["cloup"]
dev = ["black", "py-spy", "pytest"]
ipy = ["ipykernel", "ipywidgets"]
docs = [
    "mkdocs",
    "mike",
    "mkdocs-jupyter",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-macros-plugin",
    { include-group = "ipy" },
]
all = [
    { include-group = "cli" },
    { include-group = "dev" },
    { include-group = "ipy" },
    { include-group = "docs" },
]

[project.urls]
Homepage = "https://pyrception.readthedocs.io/en/stable/"
Documentation = "https://pyrception.readthedocs.io/en/stable/"
Issues = "https://github.com/cantordust/pyrception/issues"
Repository = "https://github.com/cantordust/pyrception"

[tool.ruff.format]
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ruff.lint.isort]
from-first = false
force-single-line = true
force-sort-within-sections = true
length-sort = true
lines-after-imports = 1
order-by-type = true
forced-separate = [
    "future",
    "typing",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
    "pyrception",
]
relative-imports-order = "closest-to-furthest"
