[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
authors = [{ name = "Alexander Hadjiivanov" }]
name = "pyrception"
version = "0.2.3"
dependencies = [
    "av",
    "cloup",
    "furo",
    "h5py",
    "imageio[ffmpeg]",
    "ipykernel",
    "ipympl",
    "jupyter_rfb",
    "line_profiler",
    "loguru",
    "manim",
    "matplotlib",
    "nbsphinx",
    "numba",
    "numpy",
    "opencv-python",
    "pyqtgraph",
    "PySide6",
    "python-decouple",
    "scikit-image",
    "scipy",
    "sphinx",
    "tqdm",
]

[project.optional-dependencies]
gui = []
cli = []

[project.scripts]
pyrception = "pyrception.gui.main:run"